### ISSUE TITLE
Reduce amount of indexes when using `viur-core>=3.6`

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-scriptor#14]
Hi!

viur-scriptor currently requires further indexes when used within a project that uses `viur-core>=3.6`. This is because v3.6 comes with the default_order features.

The additionally required indexes are:
```yaml
- kind: viur-script-node
  properties:
  - name: plugin
  - name: sortindex

- kind: viur-script-leaf
  properties:
  - name: plugin
  - name: sortindex
```
This seems wrong, as the only required index before was, and still should be enough:
```yaml
- kind: viur-script-leaf
  properties:
  - name: parententry
  - name: sortindex

- kind: viur-script-node
  properties:
  - name: parententry
  - name: sortindex
```

The newly added indexes are required by viur-core>=3.6 projects, but shouldn't!
![shot-2024-04-30_20-28-00](https://github.com/viur-framework/viur-scriptor/assets/16870072/a0222228-90a3-4de4-8ee3-643699247153)

Therefore, two proposals:

1. Simple but ugly: Try to run the current request with the parententry to the root node, this should avoid the requirement for an index on the `plugin` property
2. Otherwise, enhanced but better: Just request the script's node tree as already done, and check there for `plugin=True` setting, which will also reduce the amount of requests in the end. Nodes with `plugin=True` will be handled differently in this case. 

The second proposal is the better option.
